# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.125
neo_version_range=[21.1.125,)
loader_version_range=[4,)
create_version=6.0.2-36
ponder_version=1.0.44
flywheel_version=1.0.1-11
registrate_version=MC1.21-1.3.0+50
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_id=createendertransmission
mod_name=Create Ender Transmission
mod_license=All Right Reserved
mod_version=2.1.1-1.21.1
mod_group_id=com.forsteri.createendertransmission
mod_authors=Forsteri
pack_format_number=15
mod_description=\
  "Non-dimensional Machanines  \
  \
  Have you ever feel like you have lost your mind at formating networks?\
  Well, this mod is for you!\
  "